README.md
required by CommonMark spec; GitHub will render them as headers without spaces, but NPM does not: https://www.npmjs.com/package/proj4
I'm in the process of creating a PR that will add Meteor packaging to proj4js, so you will get a PR for that soon. But I thought regardless of whether you decide you want to support that, you might want these minor changes to the README so the docs will render properly on npmjs.com.
Thank you for proj4js, it's a terrific tool.
=> adding spaces after # headers in README for proper rendering

lib/constants/units.js, lib/projString.js, test/testData.js
This adds units constants for ft and us-ft, so the to_meter property can be set properly in the projString parser.
=> Add handling for +units in projString

lib/projections/stere.js, lib/wkt.js, test/testData.js
WKT definitions for stereographic projections on the Southern hemisphere use projection names that are not listed as names in `stere.js`. Also, WKT definitions for such SRSs lack a definition of the standard parallel, which I covered in an extra cleanup step.
=> Fix WKT handling for stereographic projections on Southern hemisphere

lib/datum.js
This change fixes the issue described at https://github.com/proj4js/proj4js/issues/141 by copying the datum_params object and change the copy, instead of changing the original.
=> Fix issue with custom 7 point projection

lib/wkt.js, test/test.js
Fix for https://github.com/proj4js/proj4js/issues/156
6370997 is the normal earth radius, borrowed from https://github.com/openlayers/ol3/blob/master/src/ol/sphere/normal.js#L11
If anyone has a more appropriate earth radius value, feel free to suggest it.
=> Use proper to_meter conversion factor for OGC WKT GEOGCS

stylesheets/stylesheet.css
It is misleading to provide a source download in such a prominent place, because people expect the dist files in there.
=> Hide download buttons

lib/constants/grids.js
IE8 chokes on `exports.null` in `lib/constants/grids.js` because it gets a bit confused by null meaning _null_. The attached fix doesn't change the structure of the object but it avoids the IE8 issue by putting it in quotes.
=> Fix IE8 bug caused by exports.null

README.md, package.json, publish.sh
As explained in   #208 the Jam-config is used by webpack when requireing/importing proj4. This means that the minifed version is imported, which triggers a webpack-warning.
Jam seems to be discontinued (https://github.com/caolan/jam), so the easiest solution to this problem is to remove the jam-config
=> Remove jam config

lib/common/adjust_zone.js, lib/projections/tmerc.js, lib/projections/utm.js, test/test.js, test/testData.js
Reason of doing this is because calculation results for `proj4js` and `cs2cs` differed by a large margin and it meant that there is an issue in the `tmerc` projection calculations.
More details here https://github.com/proj4js/proj4js/issues/187
Hugely inspired by `mapshaper-proj` and how `tmerc` projection is calculated there https://github.com/mbloch/mapshaper-proj/blob/master/src/projections/tmerc.js
- Added common function to adjust zone, called adjust_zone
- Fixed `tmerc` / `utm` projection calculations that were not accurate enough
- Adjusted test data for the more precise calculations
=> Fix tmerc / utm projection calculations

lib/common/adjust_zone.js, lib/projections/etmerc.js, lib/projections/utm.js, package.json, test/test.js
paging @theashyster as this effects some code he wrote, basically what he did involved a formula that for some reason required the zone to be one lower then it really was but also seemed to have a floating point error in it, so this reverts to the old formula which doesn't require the zone to be one less so that's why it touches the the adjust lon stuff, I probably need some tests to check zones 0 and 60 while I'm at it
=> fix floating point reversion (#237)

lib/parseCode.js, test/testData.js
2 fixes here, first if a proj string is defined in the wkt, lets prefer that as it's probably more accurate (from our perspective), (fixes #272), next lets look if it's spherical Mercator and if it is, lets just grab our predifined version of that as not all the wkt actually bother to say it needs to be spherical (Fixes #220)
=> parsing updates

Gruntfile.js, lib/includedProjections.js, lib/projections/robin.js, projs.js, test/testData.js
I have added robinson projection (with tests).
Note that the results are slightly different than what cs2cs would produce, the reason being that the polynomial coefficients in https://github.com/OSGeo/proj.4/blob/master/src/PJ_robin.c#L20 are stored as single-precision floats, but JavaScript uses double precision. When I recompiled proj4 code to use doubles, the results matched exactly.
=> Add robinson projection

lib/datumUtils.js
JS execution stops when geodeticToGeocentric returns null point and throws exception that p is null. 
I think it will be much better if it returns somehow like in c++ proj4 function pj_geodetic_to_geocentric.c:409.
At least in openlayers when View proj is EPSG:28405 but Layer proj is EPSG:3857 it will draw something, not just stop on exception.
Without fix:
With fix:
=> Fix error when geodeticToGeocentric returns null

Gruntfile.js, lib/core.js, test/test.js
The fix in #245 as fix for #230 is not working for all cases.
This fix also adds a solution when using an array as coords (with z or z and m value).
=> Addition to #230, added support for array coords

lib/projections/gstmerc.js
I'm pretty sure `gstmerg` is a typo and it should be `gstmerc` instead. I've added `gstmerc` as a name but kept `gstmerg` to preserve backwards compatibility. ✌🏽
=> Add "gstmerc" as a name for the gstmerc projection

lib/core.js
When a `forward` or `inverse` transform fails, it returns `null`. But our core transformer does not handle that.
By setting the `x` and `y` coordinates to `NaN` in such cases, we can successfully handle such conversions, and the consumer still knows that something went wrong by looking at the `x` and `y`.
This also fixes openlayers/openlayers#10267.
=> Do not fail on null transformedArray

README.md
Currently, the build status is shown for the last build (i.e. any branch or pull request).
=> Show travis-ci badge for the main branch

lib/parseCode.js, lib/projString.js, lib/projections/etmerc.js, lib/projections/tmerc.js, test/test.js, test/testData.js
Similar to what OSGeo/PROJ#1234 did, we are changing the default implementation for Transverse Mercator from `tmerc` to `etmerc`. Extended Transverse Mercator will now be used for all calculation, except when `+approx` is present in the proj string or `PROJECTION["Fast_Transverse_Mercator"]` is set in the WKT.
After this change, the results of cs2cs and proj4 are equal for WKT defs that use UTM zones. With proj strings, these transforms have been working correctly because `etmerc` is used for `+proj=utm` already.
Fixes #362 
Fixes #372
=> Change default Transverse Mercator algorithm

lib/projString.js, lib/projections/omerc.js, test/testData.js
Not really sure the best way to bring this into the main proj4js repository, but I added a couple changes that allow for the gamma and alpha to properly get resolved. 
The main fix with this is that when a gamma is defined as 0 in the proj string, `gam` should be true and should go through the rest of the equations.
This pull request builds on #317 
Fixes #375
=> Omerc accuracy

lib/projections/omerc.js, test/testData.js
_This implementation is based off of the mapshaper-proj implementation of [omerc](https://github.com/mbloch/mapshaper-proj/blob/master/src/projections/omerc.js), which is based directly off of the proj4 implementation of [omerc](https://github.com/OSGeo/proj.4/blob/master/src/projections/omerc.cpp). I attempted to match the structure of proj4js as best as possible._
Also, **one test I added is failing**. The test data I have added is coming from proj4, so it should be correct. It could indicate that there is more work to be done for this implementation.
This issue is mentioned in #308 , #313 , #301 , #273 , #308 , #173, and #146.
The omerc projection is returning inaccurate values. As mentioned in #308, it appears as though the implementation is ignoring the `+gamma` value. Additionally, …
=> Increase accuracy with omerc projection

lib/Proj.js, lib/projections/lcc.js, test/testData.js
This allows suporting, for example: https://epsg.io/3448
More information about the projection can be found here: https://proj.org/operations/projections/lcc.html
=> Add support for Lambert Conformal Conic 1SP

lib/constants/Datum.js
This PR updates the Helmert transform parameters to match what Proj is doing https://github.com/OSGeo/PROJ/blob/master/src/datums.cpp#L52 (at least before they updated Potsdam once more to use the Beta 2007 grid file). Also all the other datums that both projects have in common should use the same parameters now.
Fixes #385.
=> Update Hermannskogel and Potsdam to 7 parameter Helmert transform

README.md, lib/core.js, lib/transform.js, test/test.js
Between v2.6.0 and v2.6.1 we switched from always using `[x,y]` axis order to enforcing the axis order defined in the proj or wkt string. This was considered a fix, but I think it should have been considered a breaking change.
I did some research to see what the `proj` project does: they have a `proj` function which uses `[x,y]` axis order, and a `cs2cs` function which enforces the axis order of the CRS.
This pull request suggests changing the default behavior back to what we had before v2.6.1, and introduce a 2nd argument `enforceAxis` to the `forward()` and `inverse()` functions of the object returned by `proj4(fromProjection, toProjection)`. This way, users can easily opt in to enforcing CRS axis order.
Fixes #391.
=> Fix API-breaking introduction of axis order enforcement

lib/projections/lcc.js
this two names are missing from lcc names.
"Lambert Conic Conformal (1SP)",
"Lambert Conic Conformal (2SP)",
=> add two name in lcc projections

Gruntfile.js, lib/Proj.js, lib/includedProjections.js, lib/projections/geos.js, projs.js, test/testData.js
Closes #404
As described in #404, this is an implementation of the 'geos' projection based on the PROJ C library and copied from a custom internal implementation my group was using. The original javascript for the geos projection was hacked into the compiled source for proj4js so I copied it over and did the necessary changes to make it look like the other projection modules here. Keep in mind while reviewing that javascript is not my thing so feel free to comment on style, question why something is done, etc. That said, I'm very familiar with the pyproj library (Python wrapper around PROJ C) and the general concept of projections.
I've only added one test so far and it fails locally so I'm making this PR now to get some further advice. My questions are:
1. What should forward/inverse …
=> Add 'geos' projection

lib/transform.js, test/test.js
This fixes #306 where a coordinates object passed to `proj4` may be modified (depending on the transform in use).
This PR makes the following changes
- Add test to ensure that the input coordinates are not modified
- Clone the coordinates object in `transform`
=> Bugfix/306 - proj4 modify the input object after a transformation

lib/projections/stere.js, test/testData.js
In the [documentation](https://proj.org/operations/projections/stere.html) it is stated that for the the stereographic projection all parameteres are optional.
However, as pointed out in #290, calling the projection with missing x_0, y_0, lat0 or lon0 returns NaN values.
I added the missing default parameters and a new test case.
Fixes #290
=> Added missing default parameters to stere projection

lib/projections/stere.js, lib/projections/sterea.js, package-lock.json, package.json, test/testData.js
Fixes #433.
Handles WKT Polar_Stereographic strings with stere projection instead of sterea to match proj string behavior.
Adds tests for WKT Polar_Stereographic.
Updates to wkt-parser 1.3.3 for Polar_Stereographic parsing fixes.
=> Use stere instead of sterea for WKT Polar_Stereographic

lib/projections/stere.js, test/testData.js
Fixed #438, proj4 returns Infinity, -Infinity for stere with lat_ts set to 90
Added check to be sure lat_ts is not at a pole before recalculating k0
=> Fix for issue 438, proj4 returns Infinity, -Infinity for stere

lib/constants/Datum.js
This pull request adds the "Militar-geographische Institut" datum used in Austria.
=> Define MGI datum

lib/projections/sterea.js
This pull request replaces custom hypotenuse calculation code in sterea.js with the existing `hypot()` function.
=> Use existing hypot function in sterea

README.md, lib/Proj.js
As discussed in #470, proj4js sometimes throws errors that only contain the wkt string, but not more info about why the error was thrown. This is a bit more refined now.
Addtionally, the readme links to the [wkt-parser](https://github.com/proj4js/wkt-parser) now and mentions that wkt strings have to be provided in the old format.
Closes #470
=> Refine errors and documentation about supported wkt strings

lib/core.js, test/test.js
`splice()` mutates the input array, `slice()` does not.
Fixes #474
=> Do not mutate input array

lib/constants/units.js, lib/global.js
The us-ft units were changed in #480. This pull request changes them back to the more precise previous definitions.
The UTM south codes (EPSG:32701 to EPSG:32760) had an incorrect definition. This fixes them.
=> Fix us-ft and UTM south defs

lib/constants/Datum.js, test/testData.js
This pull request fixes the name of the OSGB1936 datum, and makes use of the previously unused `datumName` property of the pre-defined datums to make them discoverable also by the name. This makes many WKT definitions work more accurately than before, because the TOWGS84 param can be found now.
=> Fix OSGB1936 datum, add datum lookup by datumName

lib/nadgrid.js, package-lock.json, package.json
This is achieved by adding minimal types for the geotiff.js api, instead of importing types.
Fixes #516
=> Make geotiff a dev depencency again

README.md
Since `@types/proj4` isn't needed anymore and is deprecated, update the readme to match.
=> readme: update TypeScript instructions
