test/amd.html
The path to the curl module has changed.
=> Fix amd tests

lib/projString.js, test/test.js
Fixes a regression introduced with 5c64b03362dc9c3113ee241c530c41d67b3a29b1.
Fixes #142.
=> Re-add units to srs definition

REFERENCES.md
Add links and minor corrections.
=> Improve REFERENCE.md

Gruntfile.js
=> Fix standalone build and add ortho to default build

README.md
Improvements of this typescript definition are welcomed.
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/proj4
To install
```bash
$ typings install --save --global dt~proj4
```
=> Added Typescript definition to DT

.gitignore, Gruntfile.js, lib/datumUtils.js, lib/deriveConstants.js, lib/index.js, lib/projString.js, lib/transform.js, lib/version-browser.js, lib/version.js, package.json, publish.sh
=> beter versioning

lib/Proj.js, lib/constants/Ellipsoid.js, lib/deriveConstants.js, test/testData.js
basically #241 but I put the ellipse check in a slightly different spot where we do similar checks, fixes #240
=> fix ellipse issue

lib/constants/values.js, lib/projections/moll.js, test/testData.js
=> fix mollweide projection infinite loop

lib/projections/sterea.js
This resolves proj4js/proj4js#269.
=> Added support for 'Double_Stereographic' WKT projection

lib/projections/stere.js, test/testData.js
Described in Issue #193. For the correct formula, see 21-15 on page 159 of Synder: https://pubs.usgs.gov/pp/1395/report.pdf
=> Fixed calculation for angular distance c, see Snyder 1987, formula 21-15

.travis.yml
travis build has been failing, lets see if this fixes it
=> update node file for build

lib/adjust_axis.js, package.json, test/test.js
Replaces #300 - this is just a rebased version with two additional commits to bring in the correct version of wkt-parser and to fix indentation.
Fixes #297
=> Axis order

lib/projections/aeqd.js, lib/projections/laea.js, lib/transform.js, test/testData.js
This adds some tests for AEQD and LAEA (and one commented out test that doesn't work that I can't figure out how to fix).
The principal fixes are to make the origin point of the projection map correctly to 0,0
This fixes mostly #340 and #341
=> Fix problems with AEQD and LAEA especially at the origin point

lib/adjust_axis.js, test/test.js
Converting between +axis=enu and +axis=esu is expected to invert the y coordinate.
Resolves #352.
=> Revert a change that broke axis inversion.

lib/projections/lcc.js
update the comments 
reference: https://en.wikipedia.org/wiki/Lambert_conformal_conic_projection
=> Update comments of lcc.js

lib/projections/aea.js
Fixes https://github.com/proj4js/proj4js/issues/408
=> Remove the third parameter for running the qsfnz function

package.json
=> Add homepage entry to package.json

lib/constants/Ellipsoid.js, test/testData.js
=> Add Clarke 1880 (IGN) spheroid

lib/transform.js, test/test.js
=> Allow null points when removing unused z

lib/projections/etmerc.js
=> Add Gauss Kruger alias to Transverse Mercator

Gruntfile.js, index.js, lib/includedProjections.js, lib/projString.js, lib/projections/eqearth.js, projs.js, test/testData.js
=> Add equal earth projection

Gruntfile.js, index.js, lib/includedProjections.js, lib/projections/bonne.js, projs.js, test/testData.js
=> Add the Bonne projection

lib/constants/units.js
Added more unit types to match Proj4 to address issue: 
add support for more unit types in projection definitions
Fixes #480
=> Update units.js to add all units supported by Proj4

README.md, lib/global.js
=> Add WGS84 / UTM zones as predefined CRS

lib/global.js
See https://github.com/proj4js/proj4js/pull/482#issuecomment-2443686916
=> Start UTM zone defs at 32601 and 32701 instead of 32600 and 32700

lib/constants/units.js
=> Fix to_meter for decimeters

package-lock.json, package.json, publish.sh
Fixes build issues with the wkt-parser dependency.
=> Update dependencies and publish script

.npmignore, README.md, lib/nadgrid.js, package.json
* Improve explanation of GeoTIFF usage in `README.md`
* Simplify `readGeotiffGrid()` by making it an `async` function
* Add `test` and `scripts` to `.gitignore` for smaller package size
* Remove `"directories"` entry from `package.json`
=> Code and package cleanup

lib/index.js, package-lock.json, package.json
=> Fix type imports for mgrs and geotiff

index.d.ts, package-lock.json, package.json, tsconfig.json
=> Fix exported types namespace

index.d.ts
=> Re-export types for convenience

README.md, lib/global.js
These complement EPSG 32601...32660 and 32701...32770, which cover the rest of the world.
=> Add EPSG 5041, 5042 to predefined
